### ISSUE TITLE
Build failure, cmake does not find boost::filesystem

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/conan-h5cpp#2]
`conan install h5cpp/0.0.4@ess-dmsc/stable --build=missing` is failing for me on Ubuntu 16.04 with Conan 1.0.3. I updated Conan in case that was the problem, it was also failing with the previous version I had, which I think was 0.37.0.

I'd appreciate some help/advice to track down the problem.

```
CMake Error at src/h5cpp/CMakeLists.txt:21 (add_library):
  Target "h5cpp" links to target "Boost::filesystem" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


-- Generating done
-- Build files have been written to: /home/jonmd/.conan/data/h5cpp/0.0.4/ess-dmsc/stable/build/bf65e49a831fb5e558ec654c9c19d910610f512a/h5cpp-0.0.4/build
h5cpp/0.0.4@ess-dmsc/stable: 
h5cpp/0.0.4@ess-dmsc/stable: ERROR: Package 'bf65e49a831fb5e558ec654c9c19d910610f512a' build failed
h5cpp/0.0.4@ess-dmsc/stable: WARN: Build folder /home/jonmd/.conan/data/h5cpp/0.0.4/ess-dmsc/stable/build/bf65e49a831fb5e558ec654c9c19d910610f512a
ERROR: h5cpp/0.0.4@ess-dmsc/stable: Error in build() method, line 65
        cmake.configure(source_dir="..", build_dir=".")
        ConanException: Error 256 while executing cd '.' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="5.4" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++" -DCMAKE_INSTALL_PREFIX="" -Wno-dev '..'
```

**Comment by amues** [comment]
I believe this was caused by the older version of CMake that is installed on Ubuntu 16.04 by default. I've added _cmake_installer_ for CMake 3.10.0 as a build requirement to the new recipe _h5cpp/0.0.4-dm1@ess-dmsc/testing_. @matthew-d-jones, could you try running
```
conan install . h5cpp/0.0.4-dm1@ess-dmsc/testing --build=outdated
```
?

**Comment by matthew-d-jones** [comment]
Thanks @amues that works!
I didn't think about that, I use the version of CMake bundled with CLion, but the Conan builds were using the system installed version of course.

**Comment by amues** [comment]
I've just uploaded the _stable_ version _h5cpp/0.0.4-dm1@ess-dmsc/stable_.
